// ** TASK UPDATER: **
// CREATE A FUNCTION THAT HANDLES UPDATING THE LOCAL TASK'S STATE

// REQUIREMENTS:
// 1. UPDATE CURRENT TASK RECORD (ADLCARETASK)
// 2. FIND AND REMOVE CURRENT TASK RECORD FROM LIST OF ADLCARETASKS
// 3. ADD UPDATED CURRENT TASK TO ADLCARETASK RECORDS
// 4. PUSH TO STATE
